export enum MemoryTypes {
  byte = 'byte',
  int = 'int',
  int32 = 'int32',
  uint32 = 'uint32',
  int64 = 'int64',
  uint64 = 'uint64',
  dword = 'dword',
  short = 'short',
  long = 'long',
  float = 'float',
  double = 'double',
  bool = 'bool',
  boolean = 'boolean',
  ptr = 'ptr',
  pointer = 'pointer',
  str = 'str',
  string = 'string',
  vec3 = 'vec3',
  vector3 = 'vector3',
  vec4 = 'vec4',
  vector4 = 'vector4',
}
